# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

strategy:
  matrix:
    linux_node_14:
      imageName: 'ubuntu-20.04'
      node_version: 14.x
    linux_node_latest:
      imageName: 'ubuntu-20.04'
      node_version: 16.x
    mac_node_latest:
      imageName: 'macos-10.15'
      node_version: 16.x
    windows_node_latest:
      imageName: 'windows-2019'
      node_version: 16.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: npm ci
  - script: npm run build
  - script: npm run test-azure

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
